variable dest {}
variable env {}
variable "nodeuser" {}
variable "nodesshfilename" {}
variable "nodesshfile" {}
variable "nodesshpub" {}
variable gcp_region {}
variable cluster_name {}
variable how_many_master_nodes {}
variable how_many_worker_nodes {}
variable mgmt_subnet_cidr {}
variable private_subnet_cidr {}
variable public_subnet_cidr {}
